const transactionDummyData = [
  {
    senderId: 1,
    receiverId: 8,
    restaurantId: 2,
    transactionId: 1,
    productEmoji: "🥘",
    senderName: "John Doe",
    receiverName: "Jane Doe",
    productName: "Product X",
    restaurantName: "Shop ABC Chole centre",
    senderImage: require("../assets/images/pfp1.png"),
  },
  {
    senderId: 2,
    receiverId: 3,
    restaurantId: 4,
    productEmoji: "🍲",
    transactionId: 2,
    senderName: "Alice Smith",
    receiverName: "Bob Johnson",
    productName: "Product Y",
    restaurantName: "Shop XYZ",
    senderImage: require("../assets/images/pfp2.png"),
  },
  {
    senderId: 1,
    receiverId: 8,
    restaurantId: 2,
    transactionId: 3,
    productEmoji: "🍕",
    senderName: "John Doe",
    receiverName: "Jane Doe",
    productName: "Product Z",
    restaurantName: "Shop ABC",
    senderImage: require("../assets/images/pfp1.png"),
  },
  {
    senderId: 2,
    receiverId: 3,
    restaurantId: 4,
    productEmoji: "🥞",
    transactionId: 4,
    senderName: "Alice Smith",
    receiverName: "Bob Johnson",
    productName: "Product P",
    restaurantName: "Shop XYZ",
    senderImage: require("../assets/images/pfp2.png"),
  },
  {
    senderId: 1,
    receiverId: 8,
    restaurantId: 2,
    productEmoji: "🍰",
    transactionId: 5,
    senderName: "John Doe",
    receiverName: "Jane Doe",
    productName: "Product K",
    restaurantName: "Shop ABC",
    senderImage: require("../assets/images/pfp1.png"),
  },
  {
    senderId: 2,
    receiverId: 3,
    restaurantId: 4,
    productEmoji: "🍥",
    transactionId: 6,
    senderName: "Alice Smith",
    receiverName: "Bob Johnson",
    productName: "Product M",
    restaurantName: "Shop XYZ",
    senderImage: require("../assets/images/pfp2.png"),
  },
  {
    senderId: 1,
    receiverId: 8,
    restaurantId: 2,
    productEmoji: "🍛",
    transactionId: 7,
    senderName: "John Doe",
    receiverName: "Jane Doe",
    productName: "Product R",
    restaurantName: "Shop ABC",
    senderImage: require("../assets/images/pfp1.png"),
  },
  {
    senderId: 2,
    receiverId: 3,
    restaurantId: 4,
    productEmoji: "🍨",
    transactionId: 8,
    senderName: "Alice Smith",
    receiverName: "Bob Johnson",
    productName: "Product B",
    restaurantName: "Shop XYZ",
    senderImage: require("../assets/images/pfp2.png"),
  },
];

export default transactionDummyData;
